package relay

import (
	"bufio"
	"crypto/rand"
	"encoding/hex"
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/ohstr/ncli/cli/common"
	"github.com/ohstr/ncli/cli/keyresolve"
	"github.com/ohstr/ncli/client"
	"github.com/rs/zerolog/log"
	"github.com/spf13/cobra"
)

// relaysDirName is the subdirectory of common.AppConfigDir() under which
// createRelayContext lays out each relay it creates:
// relays/<name>/{relay.yaml, store.db, logs/}.
const relaysDirName = "relays"

// runOrCreateRelayContext resolves the -c/--context flag: if name is
// already a saved relay context, it points viper at that context's config
// file for this invocation only (unlike `relay context use`, it never
// touches CurrentRelayContext). If name isn't saved yet, it creates one --
// a minimal relay.yaml backed by --identity or a freshly generated
// identity, under common.AppConfigDir()/relays/<name>/ -- then does the
// same.
//
// This runs independently of ncli.InitConfig's own --config/context/cwd
// resolution (cli/ncli/root.go's resolveConfigFile), which already ran (as
// root's PersistentPreRun) before this PreRunE. -c/--context is an
// explicit, higher-priority override of that: it loads its target
// directly into viper here, replacing whatever config layer
// resolveConfigFile already loaded.
func runOrCreateRelayContext(cmd *cobra.Command, name string) error {
	if cfgFile, _ := cmd.Flags().GetString("config"); cfgFile != "" {
		return common.UsageError(cmd, errors.New("--config and --context/-c are mutually exclusive"))
	}
	if !validRelayContextName(name) {
		return common.InvalidInputError(cmd, name, fmt.Errorf("relay context name %q must not be empty, \".\", \"..\", or contain a path separator", name))
	}

	jsonMode, _ := cmd.Flags().GetBool("json")
	quiet, _ := cmd.Flags().GetBool("quiet")

	prefs, err := client.LoadPrefs()
	if err != nil {
		return common.RuntimeError(cmd, err)
	}

	path, ok := prefs.RelayContexts[name]
	if !ok {
		// A warning, not narration -- AGENTS.md's own output convention
		// keeps warnings visible under both --json (JSON-formatted, same
		// as every other stderr line) and -q/--quiet (which only drops
		// info-level narration); only the interactive prompt itself is
		// skipped in either of those, since --json has no TTY to prompt
		// on and -q means "don't ask, just go".
		log.Warn().Msgf("relay context %q does not exist", name)
		if !jsonMode && !quiet {
			stdin := bufio.NewReader(os.Stdin)
			if !common.PromptYesNo(stdin, "Create it now (minimal config + new identity)? [y/N] ") {
				return common.UsageError(cmd, fmt.Errorf("relay context %q not created", name))
			}
		}

		path, err = createRelayContext(cmd, jsonMode, name)
		if err != nil {
			return err
		}
	}

	if err := common.LoadViperConfig(path); err != nil {
		// The context's own config file failed to parse -- a malformed
		// supplied value, same as initConfig's viper.Unmarshal failure
		// just below in the normal case (CodeInvalidInput, "unable to
		// decode config"), not an unexpected/internal failure. name (not
		// the YAML error's own value) is the one clean identifier here.
		return common.InvalidInputError(cmd, name, fmt.Errorf("relay context %q: %w", name, err))
	}
	common.ActiveRelayContext = name
	return nil
}

// validRelayContextName guards the path.Join below: name becomes a
// directory component under common.AppConfigDir(), so anything that could
// escape that directory (a path separator, "..") or resolve to it
// directly (".") is rejected outright rather than silently normalized.
func validRelayContextName(name string) bool {
	if name == "" || name == "." || name == ".." {
		return false
	}
	return !strings.ContainsAny(name, `/\`)
}

// createRelayContext builds a brand-new minimal relay under
// common.AppConfigDir()/relays/<name>/ (relay.yaml, store.db, logs/),
// backed by --identity if given or a freshly generated+vault-saved
// identity otherwise, and registers it as a saved relay context. Returns
// the new config file's path.
func createRelayContext(cmd *cobra.Command, jsonMode bool, name string) (string, error) {
	identityFlag, _ := cmd.Flags().GetString("identity")

	privKeyHex, err := resolveContextIdentity(cmd, jsonMode, name, identityFlag)
	if err != nil {
		return "", err
	}

	dir := filepath.Join(common.AppConfigDir(), relaysDirName, name)
	if err := os.MkdirAll(dir, 0755); err != nil {
		return "", common.RuntimeError(cmd, fmt.Errorf("failed to create relay directory: %w", err))
	}

	storePath := filepath.Join(dir, "store.db")
	logDir := filepath.Join(dir, "logs")
	cfgPath := filepath.Join(dir, "relay.yaml")

	yamlContent := fmt.Sprintf(`# Generated by "ncli relay --context %s".
nip11:
  name: %q
  privkey: %q
store: %q
logdir: %q
`, name, name, privKeyHex, storePath, logDir)

	if err := os.WriteFile(cfgPath, []byte(yamlContent), 0600); err != nil {
		return "", common.RuntimeError(cmd, fmt.Errorf("failed to write %s: %w", cfgPath, err))
	}

	prefs, err := client.LoadPrefs()
	if err != nil {
		return "", common.RuntimeError(cmd, err)
	}
	if _, err := prefs.AddRelayContext(name, cfgPath); err != nil {
		return "", common.RuntimeError(cmd, err)
	}
	if err := client.SavePrefs(prefs); err != nil {
		return "", common.RuntimeError(cmd, err)
	}

	if !jsonMode {
		log.Info().Str("context", name).Str("config", cfgPath).Msg("relay context created")
	}
	return cfgPath, nil
}

// resolveContextIdentity returns the private key to embed in a newly
// created context's relay.yaml: identityFlag resolved via the same
// vault-label/nsec/npub/hex/nprofile/nip-05 rules as every other
// --identity flag in ncli (requiring a private key, same as bunker's
// ResolveSignerKey) if given, or a freshly generated identity saved to
// the vault under label name (suffixed with a random 4-hex tag on a label
// collision) otherwise.
func resolveContextIdentity(cmd *cobra.Command, jsonMode bool, name, identityFlag string) (string, error) {
	if identityFlag != "" {
		resolved, err := client.ResolveIdentifier(identityFlag)
		if err != nil {
			return "", keyresolve.ClassifyIdentifierError(cmd, identityFlag, err)
		}
		privKeyHex, err := keyresolve.ResolveSigningKey(cmd, jsonMode, resolved)
		if err != nil {
			return "", err
		}
		if privKeyHex == "" {
			return "", common.AuthError(cmd, fmt.Errorf("identity %q has no private key available", common.RedactSecretInput(identityFlag)))
		}
		return privKeyHex, nil
	}

	id, err := client.GenerateIdentity()
	if err != nil {
		return "", common.RuntimeError(cmd, err)
	}

	vaultPrivKeyHex, err := keyresolve.UnlockOrCreateVault(cmd, jsonMode)
	if err != nil {
		return "", err
	}

	label := name
	for attempt := 0; ; attempt++ {
		entry, err := client.AddVaultEntry(vaultPrivKeyHex, label, id.PrivKeyHex)
		if err == nil {
			if !jsonMode {
				log.Info().Str("label", entry.Label).Msg("new identity saved to vault")
			}
			return id.PrivKeyHex, nil
		}
		if !errors.Is(err, client.ErrLabelExists) {
			return "", common.RuntimeError(cmd, fmt.Errorf("failed to save identity: %w", err))
		}
		if attempt >= 5 {
			return "", common.ConflictError(cmd, label, err)
		}
		label = name + "-" + randomHexSuffix()
	}
}

// randomHexSuffix returns 4 random lowercase hex characters (2 bytes),
// used to disambiguate a vault label collision without an interactive
// prompt.
func randomHexSuffix() string {
	b := make([]byte, 2)
	if _, err := rand.Read(b); err != nil {
		// crypto/rand.Read only fails if the OS entropy source itself is
		// broken -- effectively unreachable in practice, and there's
		// nothing more useful to do here than fall back to a fixed tag
		// rather than propagating an error this deep into identity
		// creation.
		return "0000"
	}
	return hex.EncodeToString(b)
}
